# action.yml
name: 'Build Claud Desktop'
description: 'build an appimage for Claude Desktop'
inputs:
  build-arg:
    description: 'arg for builder'
    required: false
    default: 'appimage'
outputs:
  time: # id of output
    description: 'The time it took to build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --build
    - ${{ inputs.build-arg }}
    - --clean
    - yes
