# action.yml
name: 'Build Claud Desktop'
description: 'build an appimage for Claude Desktop'
outputs:
  time: # id of output
    description: 'The time it took to build'
runs:
  using: 'docker'
  image: 'Dockerfile'
