name: Build Package (Reusable)

on:
  workflow_call:
    inputs:
      build_flags:
        description: 'Flags to pass to build.sh (e.g., "--build deb --clean no")'
        required: false
        type: string
        default: '' # Default is no extra flags
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  build:
    runs-on: ubuntu-latest # Required, but overridden by caller if specified there

    steps:

    - name: Update package lists
      run: |
        sudo apt-get update

    - name: Make build script executable
      run: chmod +x ./build.sh

    - name: Run build script
      run: |
        echo "Running build with flags: ${{ inputs.build_flags }}"
        sudo ./build.sh ${{ inputs.build_flags }} # Use sudo for apt install within build.sh