name: claude-desktop-appimage

on: [push]

env:
  APPIMAGE_EXTRACT_AND_RUN: 1
  BUILT_IN_DOCKER: 1

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkoutrepo
        uses: actions/checkout@v4
      - name: mkdir output
        run: mkdir output
      - name: builder
        id: builder
        uses: joshuacox/claude-desktop-appimage@v0.0.7
      - name: Get the build time
        run: echo "The time to build was ${{ steps.builder.outputs.time }}"
      - name: Archive code coverage results
        id: archiver
        uses: actions/upload-artifact@v4
        with:
          name: claude-desktop
          path: output/claude-desktop-0.11.3-amd64.AppImage
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.7
          name: Release v0.0.7
          body: |
            This is the appimage made from this builder.
          draft: false
          prerelease: false
          files: |
            output/claude-desktop-0.11.3-amd64.AppImage
