name: ReactFoundations

on: [push]

env:
  APPIMAGE_EXTRACT_AND_RUN: 1
  BUILT_IN_DOCKER: 1

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: joshuacox/claude-desktop-appimage@v1
        with:
          build-flags: '--build appimage --clean yes'
      # Use the output from the `hello` step
      - name: Get the build time
        run: echo "The time to build was ${{ steps.hello.outputs.time }}"
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkoutrepo
        uses: actions/checkout@v4
      - name: builder
        id: builder
        uses: joshuacox/claude-desktop-appimage@v0.0.1
        with:
          build-flags: '--build appimage --clean yes'
      - name: Get the build time
        run: echo "The time to build was ${{ steps.builder.outputs.time }}"
      - name: Archive code coverage results
        id: archiver
        uses: actions/upload-artifact@v4
        with:
          name: claude-desktop
          path: output/claude-desktop-0.11.3-arm64.AppImage
      # Use the output from the `builder` step
