name: ReactFoundations

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: joshuacox/claude-desktop-appimage@v1
        with:
          build-flags: '--build appimage --clean yes'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time to build was ${{ steps.hello.outputs.time }}"
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, build, and test
        run: |
          pnpm install
          pnpm run build --if-present
          pnpm test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
