name: claude-desktop-debian

on: [push]

env:
  BUILT_IN_DOCKER: 1

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkoutrepo
        uses: actions/checkout@v4
      
      - name: Create output directory
        run: mkdir -p output

      - name: Build Debian package
        id: debbuilder
        run: |
          ./docker-builder.sh --build deb --clean yes

      - name: List output files
        run: ls -la output/

      - name: Upload deb amd64
        id: debarchiveramd64
        uses: actions/upload-artifact@v4
        with:
          name: claude-desktop-deb-amd64
          path: output/claude-desktop_*_amd64.deb

  build_and_test_arm:
    runs-on: ubuntu-latest  # ARM runners often not available, using emulation
    steps:
      - name: Checkout repository
        id: checkoutrepo
        uses: actions/checkout@v4
      
      - name: Set up QEMU for ARM64 emulation
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Create output directory
        run: mkdir -p output

      - name: Build Debian package (ARM64)
        id: debbuilder
        run: |
          # Use emulated ARM64 build
          docker build --platform linux/arm64 -t claude-desktop-debian-arm64 .
          docker run --platform linux/arm64 --rm -v ./output:/home/builder/output claude-desktop-debian-arm64 --build deb --clean yes

      - name: List output files
        run: ls -la output/

      - name: Upload deb arm64
        id: debarchiverarm64
        uses: actions/upload-artifact@v4
        with:
          name: claude-desktop-deb-arm64
          path: output/claude-desktop_*_arm64.deb